name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # required for PyPI Trusted Publishing (OIDC)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distributions
        run: python -m build

      - name: Verify metadata (twine check)
        run: python -m twine check dist/*

      # --- PRERELEASE path → TestPyPI ---
      - name: Publish prerelease to TestPyPI (Trusted Publishing)
        if: github.event.release.prerelease == true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      # --- FINAL RELEASE path → PyPI ---
      - name: Publish release to PyPI (Trusted Publishing)
        if: github.event.release.prerelease == false
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
